### ISSUE TITLE
Edge labelling on directed graphs not readable

### ISSUE THREAD

**Issue by pjoKIT** [kit-data-manager/visualization-graph-web-component#76]
The labels on directed edges are not readable when zoomed in:
![image](https://github.com/kit-data-manager/visualization-graph-web-component/assets/97529065/dd076e5e-be5a-4654-8d84-9892e0b3ecba)

**Comment by ajaykirarkit** [comment]
This issue is fixed and will be reflected in next release.

**Comment by ajaykirarkit** [comment]
Issue resolved
